
FROM centos:6

MAINTAINER "takashioshikawa" <abr3tks5200@gmail.com>


RUN yum update -y
RUN yum install -y which
RUN yum install -y wget
RUN yum install -y tar
RUN yum install -y vim
RUN yum install -y git

CMD /bin/bash
