FROM ubuntu:xenial-20160713

MAINTAINER "takashioshikawa" <abr3tks5200@gmail.com>


RUN apt-get update
RUN apt-get install -y vim
RUN apt-get install -y wget
RUN apt-get install -y git

CMD /bin/bash
